# Generated by Django 4.0.2 on 2022-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogID',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
